/** Single source of truth for error code descriptions. Auto-extracted by `doc/scripts/gen-error-codes.ts`. */
const ERROR_CODE_MEANINGS: Record<string, string> = {
  ALREADY_ORG_MEMBER: 'User is already a member of this org',
  ALREADY_PROCESSED: 'Invite or join request was already accepted/declined',
  CANNOT_MODIFY_ADMIN: 'Cannot demote or remove the last admin',
  CANNOT_MODIFY_OWNER: 'Owner role cannot be reassigned',
  CHUNK_ALREADY_UPLOADED: 'File chunk with this index was already uploaded in the session',
  CHUNK_NOT_FOUND: 'File chunk index missing from upload session',
  CONFLICT: 'Concurrent edit detected (expectedUpdatedAt mismatch)',
  EDITOR_REQUIRED: 'ACL edit permission required',
  FILE_NOT_FOUND: 'Referenced file does not exist or was already deleted',
  FILE_TOO_LARGE: 'File exceeds the configured size limit',
  FORBIDDEN: 'Caller is authenticated but lacks permission',
  INCOMPLETE_UPLOAD: 'Upload session finalized before all chunks arrived',
  INSUFFICIENT_ORG_ROLE: 'Caller lacks the required org role for this action',
  INVALID_FILE_TYPE: 'File MIME type is not in the allowlist',
  INVALID_INVITE: 'Invite token is malformed, revoked, or unknown',
  INVALID_KEY: 'Key is not in the kv table whitelist',
  INVALID_SESSION_STATE: 'Upload session is in a state that disallows the requested action',
  INVALID_WHERE: 'where clause references unknown field or invalid operator',
  INVITE_EXPIRED: 'Invite token has expired',
  JOIN_REQUEST_EXISTS: 'A join request from this user already exists',
  LIMIT_EXCEEDED: 'Bulk operation exceeded the per-call item limit',
  MUST_TRANSFER_OWNERSHIP: 'Owner cannot leave without transferring ownership',
  NOT_AUTHENTICATED: 'No active session — caller must log in',
  NOT_AUTHORIZED: 'Generic permission denial (not yet narrowed to a specific role)',
  NOT_FOUND: "Row doesn't exist OR caller doesn't own it (no-enumeration policy)",
  NOT_ORG_MEMBER: 'Caller is not a member of the target org',
  ORG_SLUG_TAKEN: 'Org slug is already in use',
  RATE_LIMITED: 'Sliding-window rate limit exceeded',
  SESSION_NOT_FOUND: 'Upload session id is unknown or expired',
  TARGET_MUST_BE_ADMIN: 'Operation requires the target user to be an admin',
  UNAUTHORIZED: 'Caller cannot perform this action (alias of NOT_AUTHORIZED in some surfaces)',
  USER_NOT_FOUND: 'Referenced user identity does not exist',
  VALIDATION_FAILED: 'Zod schema validation rejected the payload'
}
export { ERROR_CODE_MEANINGS }
