#!/usr/bin/env bun
/* eslint-disable no-console, no-continue */
/* oxlint-disable eslint-plugin-unicorn(no-process-exit) */
/** biome-ignore-all lint/style/noProcessEnv: CLI script */
/** biome-ignore-all lint/nursery/noUndeclaredEnvVars: CLI script */
/** biome-ignore-all lint/nursery/noContinue: classify-or-skip loop */
import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import type { ExtractedMeta } from '../_lib/codegen/extract-meta'
import { extractMeta } from '../_lib/codegen/extract-meta'
import { collect } from '../_lib/codegen/scan'
const TOOLS_ROOT = resolve(process.cwd(), process.env.TOOLS_ROOT ?? 'convex/tools')
const OUT = resolve(process.cwd(), process.env.DOCS_OUT ?? 'convex/tools/INVENTORY.md')
const PROVIDER_PREFIX_RE = /^_/u
const mdRow = (cells: string[]): string => `| ${cells.join(' | ')} |`
const escapeMd = (s: string): string => s.replaceAll('|', String.raw`\|`).replaceAll('\n', ' ')
const main = async (): Promise<void> => {
  const data = await collect(TOOLS_ROOT)
  const metas = extractMeta(data.tools.map(t => t.absPath))
  const toolsByProvider = new Map<string, { cliPath: string[]; meta: ExtractedMeta; tier: 'admin' | 'user' }[]>()
  for (const t of data.tools) {
    const m = metas.get(t.absPath)
    if (!m) continue
    const key = t.cliPath[0] ?? 'unknown'
    if (!toolsByProvider.has(key)) toolsByProvider.set(key, [])
    toolsByProvider.get(key)?.push({ cliPath: t.cliPath, meta: m, tier: t.tier })
  }
  const now = new Date().toISOString().slice(0, 10)
  const lines: string[] = [
    '# Tool inventory',
    '',
    '<!-- GENERATED by packages/cli/bin/x-docgen.ts — do not edit by hand. Re-run via `bun run codegen` in apps/backend. -->',
    '',
    `Generated ${now} · ${data.tools.length} tools across ${data.providers.length} provider(s).`,
    ''
  ]
  const providers = [...toolsByProvider.keys()].toSorted()
  for (const prov of providers) {
    const label = prov.replace(PROVIDER_PREFIX_RE, '')
    const tools = (toolsByProvider.get(prov) ?? []).toSorted((a, b) =>
      a.cliPath.join(' ').localeCompare(b.cliPath.join(' '))
    )
    lines.push(`## \`${label}\``, '')
    lines.push(mdRow(['Command', 'Description', 'Version', 'Deprecated']))
    lines.push(mdRow(['---', '---', '---', '---']))
    for (const t of tools) {
      const cmd = `\`${t.cliPath.join(' ').replace(PROVIDER_PREFIX_RE, '')}\``
      lines.push(
        mdRow([
          cmd,
          escapeMd(t.meta.description || '—'),
          String(t.meta.version),
          t.meta.deprecated ? escapeMd(t.meta.deprecated) : ''
        ])
      )
    }
    lines.push('')
    for (const t of tools) {
      if (t.meta.examples.length === 0 && Object.keys(t.meta.argDescriptions).length === 0) continue
      lines.push(`### \`${t.cliPath.join(' ').replace(PROVIDER_PREFIX_RE, '')}\``, '')
      if (Object.keys(t.meta.argDescriptions).length > 0) {
        lines.push('Args:', '')
        for (const [name, desc] of Object.entries(t.meta.argDescriptions))
          lines.push(`- \`--${name}\` — ${escapeMd(desc)}`)
        lines.push('')
      }
      if (t.meta.examples.length > 0) {
        lines.push('Examples:', '', '```sh')
        for (const ex of t.meta.examples) lines.push(ex)
        lines.push('```', '')
      }
    }
  }
  await mkdir(dirname(OUT), { recursive: true })
  await writeFile(OUT, `${lines.join('\n')}\n`)
  console.log(`wrote ${OUT}: ${data.tools.length} tools, ${data.providers.length} providers`)
}
await main()
