/** biome-ignore-all lint/nursery/noContinue: control flow */
/** biome-ignore-all lint/performance/useTopLevelRegex: codegen helpers */
/* eslint-disable no-continue */
import type { ToolFile } from './scan'
import type { Extracted, SchemaNode } from './schema'
const pascalCase = (s: string): string =>
  s
    .split(/[_\-/]/u)
    .filter(Boolean)
    .map(p => p.charAt(0).toUpperCase() + p.slice(1))
    .join('')
const schemaToTs = (node: SchemaNode, depth = 0): string => {
  const pad = '  '.repeat(depth)
  const padInner = '  '.repeat(depth + 1)
  if (node.kind === 'string') return 'string'
  if (node.kind === 'number') return 'number'
  if (node.kind === 'boolean') return 'boolean'
  if (node.kind === 'null') return 'null'
  if (node.kind === 'enum') return node.values.map(v => JSON.stringify(v)).join(' | ')
  if (node.kind === 'array') return `${schemaToTs(node.element, depth)}[]`
  if (node.kind === 'object') {
    const entries = Object.entries(node.shape)
    if (entries.length === 0) return '{}'
    const body = entries
      .map(([k, v]) => `${padInner}${k}${v.optional ? '?' : ''}: ${schemaToTs(v.schema, depth + 1)}`)
      .join('\n')
    return `{\n${body}\n${pad}}`
  }
  if (node.kind === 'union') return node.members.map(m => schemaToTs(m, depth)).join(' | ')
  return 'unknown'
}
const emitToolTypes = (tools: ToolFile[], schemas: Map<string, Extracted>): string => {
  const lines: string[] = [
    '// Generated by `bun build-cli.ts`. Do not edit.',
    "// Static TS types for every tool — derived from each handler's signature + return type.",
    ''
  ]
  const exportedNames: string[] = []
  for (const t of tools) {
    const ex = schemas.get(t.absPath)
    if (!ex) continue
    const name = pascalCase(t.cliPath.join('-'))
    if (ex.args) {
      lines.push(`interface ${name}Args ${schemaToTs(ex.args)}`, '')
      exportedNames.push(`${name}Args`)
    }
    lines.push(`interface ${name}Result ${schemaToTs(ex.schema)}`, '')
    exportedNames.push(`${name}Result`)
  }
  lines.push(`export type { ${exportedNames.join(', ')} }`)
  return lines.join('\n')
}
interface TreeNode {
  children?: Record<string, TreeNode>
  ref?: string
}
const renderTree = (n: Record<string, TreeNode>, indent: number): string => {
  const pad = '  '.repeat(indent)
  const entries = Object.entries(n)
    .toSorted(([a], [b]) => a.localeCompare(b))
    .map(([k, v]) => {
      if (v.ref) return `${pad}${k}: ${v.ref}`
      return `${pad}${k}: {\n${renderTree(v.children ?? {}, indent + 1)}\n${pad}}`
    })
  return entries.join(',\n')
}
const emitToolCallers = (tools: ToolFile[], schemas: Map<string, Extracted>): string => {
  const header: string[] = [
    '// Generated by `bun build-cli.ts`. Do not edit.',
    "import type { FunctionReference } from 'convex/server'",
    "import type { ActionCtx, MutationCtx, QueryCtx } from '../../_generated/server'",
    "import type { Called, Wrapped } from '@a/cli'",
    "import { internal } from '../../_generated/api'",
    "import { callResult, unwrap, wrapArgs } from '@a/cli'"
  ]
  const typeImports: string[] = []
  const tableEntries: string[] = []
  interface Emit {
    args: string
    ctxType: string
    fn: string
    key: string
    kind: 'action' | 'mutation' | 'query'
    name: string
    result: string
  }
  const emits: Emit[] = []
  for (const t of tools) {
    const ex = schemas.get(t.absPath)
    if (!ex) continue
    const name = pascalCase(t.cliPath.join('-'))
    const key = t.cliPath.join('.')
    const ctxType = t.kind === 'query' ? 'QueryCtx' : t.kind === 'mutation' ? 'MutationCtx' : 'ActionCtx'
    const argsType = ex.args ? `${name}Args` : 'Record<string, never>'
    if (ex.args) typeImports.push(`${name}Args`)
    typeImports.push(`${name}Result`)
    tableEntries.push(
      `  ${JSON.stringify(key)}: { args: ${argsType}; ctx: ${ctxType}; kind: '${t.kind}'; result: ${name}Result };`
    )
    emits.push({ args: argsType, ctxType, fn: t.fnAccessor, key, kind: t.kind, name, result: `${name}Result` })
  }
  const internals: string[] = [`import type { ${typeImports.join(', ')} } from './toolTypes'`, '']
  const callerFns: string[] = []
  const root: Record<string, TreeNode> = {}
  for (const e of emits) {
    const fnName = `call${e.name}`
    const runName = e.kind === 'query' ? 'runQuery' : e.kind === 'mutation' ? 'runMutation' : 'runAction'
    callerFns.push(
      `const ${fnName} = async (ctx: ${e.ctxType}, args: ${e.args}): Promise<Called<${e.result}>> => {`,
      `  const r = (await ctx.${runName}(${e.fn}, wrapArgs(args, ${JSON.stringify(e.key)}))) as Wrapped<${e.result}>`,
      '  return unwrap(r)',
      '}'
    )
    const parts = e.key.split('.')
    const leafKey = parts.at(-1)
    if (!leafKey) throw new Error('tree build invariant: empty key')
    let node: Record<string, TreeNode> = root
    for (let i = 0; i < parts.length - 1; i += 1) {
      const p = parts[i]
      if (!p) throw new Error('tree build invariant: empty segment')
      const existing = node[p]
      const children = existing?.children ?? {}
      if (!existing) node[p] = { children }
      node = children
    }
    node[leafKey] = { ref: fnName }
  }
  const treeLines = ['const callersTree = {', renderTree(root, 1), '} as const']
  const fnByPathEntries = emits.map(
    e =>
      `  ${JSON.stringify(e.key)}: { fn: ${e.fn} as unknown as FunctionReference<'${e.kind}', 'internal'>, kind: '${e.kind}' as const }`
  )
  const fnByPath = [
    "type FnEntry =\n  | { fn: FunctionReference<'action', 'internal'>; kind: 'action' }\n  | { fn: FunctionReference<'mutation', 'internal'>; kind: 'mutation' }\n  | { fn: FunctionReference<'query', 'internal'>; kind: 'query' }",
    'const fnByPath: Record<string, FnEntry> = {',
    fnByPathEntries.join(',\n'),
    '}'
  ]
  const exports: string[] = [
    '',
    'interface ToolTable {',
    ...tableEntries,
    '}',
    '',
    'const callers = callersTree',
    'export { callers, callResult, fnByPath }',
    "export type { Called, Wrapped } from '@a/cli'",
    'export type { ToolTable }'
  ]
  return [...header, ...internals, ...callerFns, ...treeLines, ...fnByPath, ...exports].join('\n')
}
const providerImportVar = (name: string): string => `${name.replace(/^_/u, '')}_provider`
const emitRegistry = (data: { providers: string[]; schemas: Map<string, Extracted>; tools: ToolFile[] }): string => {
  const lines: string[] = [
    '// Generated by `bun build-cli.ts`. Do not edit.',
    "import type { FunctionReference } from 'convex/server'",
    "import type { ArgSpecs, ProviderMeta, RegistryEntry, ToolMeta } from '@a/cli'",
    "import { internal } from '../../_generated/api'",
    ...data.providers.map(p => `import ${providerImportVar(p)} from '../${p}/_provider'`),
    ...data.tools.map(t => `import { ${t.exportName} as ${t.importVar} } from '${t.importPath}'`),
    'const PROVIDERS: Record<string, ProviderMeta> = {',
    ...data.providers.map(p => `  ${JSON.stringify(p)}: ${providerImportVar(p)},`),
    '}',
    "const REGISTRY: Record<string, RegistryEntry<'admin' | 'user'>> = {"
  ]
  for (const t of data.tools) {
    const extracted = data.schemas.get(t.absPath)
    lines.push(
      `  ${JSON.stringify(t.registryKey)}: {`,
      `    argSpecs: (${t.importVar} as unknown as { argSpecs: ArgSpecs }).argSpecs,`,
      `    fn: ${t.fnAccessor} as FunctionReference<'${t.kind}', 'internal'>,`,
      `    inferredDescription: ${extracted?.jsdoc ? JSON.stringify(extracted.jsdoc) : 'null'},`,
      `    inferredSchema: ${extracted?.schema ? JSON.stringify(extracted.schema) : 'null'},`,
      `    kind: '${t.kind}',`,
      `    meta: (${t.importVar} as unknown as { meta: ToolMeta }).meta,`,
      `    path: ${JSON.stringify(t.cliPath)},`,
      `    tier: ${JSON.stringify(t.tier)}`,
      '  },'
    )
  }
  lines.push('}')
  lines.push('export { PROVIDERS, REGISTRY }')
  lines.push('')
  return lines.join('\n')
}
export { emitRegistry, emitToolCallers, emitToolTypes }
