// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  contentType: __t.string().name("content_type"),
  createdAt: __t.timestamp().name("created_at"),
  filename: __t.string(),
  id: __t.u32().primaryKey(),
  size: __t.f64(),
  storageKey: __t.string().name("storage_key"),
  uploadedAt: __t.timestamp().name("uploaded_at"),
  userId: __t.identity().name("user_id"),
});
