// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Blog = __t.object("Blog", {
  attachments: __t.option(__t.array(__t.string())),
  category: __t.string(),
  content: __t.string(),
  coverImage: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  id: __t.u32(),
  published: __t.bool(),
  tags: __t.option(__t.array(__t.string())),
  title: __t.string(),
  updatedAt: __t.timestamp(),
  userId: __t.identity(),
});
export type Blog = __Infer<typeof Blog>;

export const BlogProfile = __t.object("BlogProfile", {
  avatar: __t.option(__t.string()),
  bio: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  displayName: __t.string(),
  notifications: __t.bool(),
  theme: __t.string(),
  updatedAt: __t.timestamp(),
  userId: __t.identity(),
});
export type BlogProfile = __Infer<typeof BlogProfile>;

export const Chat = __t.object("Chat", {
  createdAt: __t.timestamp(),
  id: __t.u32(),
  isPublic: __t.bool(),
  title: __t.string(),
  updatedAt: __t.timestamp(),
  userId: __t.identity(),
});
export type Chat = __Infer<typeof Chat>;

export const File = __t.object("File", {
  contentType: __t.string(),
  createdAt: __t.timestamp(),
  filename: __t.string(),
  id: __t.u32(),
  size: __t.f64(),
  storageKey: __t.string(),
  uploadedAt: __t.timestamp(),
  userId: __t.identity(),
});
export type File = __Infer<typeof File>;

export const Message = __t.object("Message", {
  chatId: __t.u32(),
  createdAt: __t.timestamp(),
  id: __t.u32(),
  get parts() {
    return __t.array(MessagePart);
  },
  role: __t.string(),
  updatedAt: __t.timestamp(),
  userId: __t.identity(),
});
export type Message = __Infer<typeof Message>;

export const MessagePart = __t.object("MessagePart", {
  file: __t.option(__t.string()),
  image: __t.option(__t.string()),
  name: __t.option(__t.string()),
  text: __t.option(__t.string()),
  type: __t.string(),
});
export type MessagePart = __Infer<typeof MessagePart>;

export const Movie = __t.object("Movie", {
  backdropPath: __t.option(__t.string()),
  budget: __t.option(__t.f64()),
  cachedAt: __t.timestamp(),
  createdAt: __t.timestamp(),
  get genres() {
    return __t.array(MovieGenre);
  },
  id: __t.u32(),
  invalidatedAt: __t.option(__t.timestamp()),
  originalTitle: __t.string(),
  overview: __t.string(),
  posterPath: __t.option(__t.string()),
  releaseDate: __t.string(),
  revenue: __t.option(__t.f64()),
  runtime: __t.option(__t.f64()),
  tagline: __t.option(__t.string()),
  title: __t.string(),
  tmdbId: __t.u32(),
  updatedAt: __t.timestamp(),
  voteAverage: __t.f64(),
  voteCount: __t.f64(),
});
export type Movie = __Infer<typeof Movie>;

export const MovieGenre = __t.object("MovieGenre", {
  id: __t.f64(),
  name: __t.string(),
});
export type MovieGenre = __Infer<typeof MovieGenre>;

export const MovieGenreInput = __t.object("MovieGenreInput", {
  id: __t.f64(),
  name: __t.string(),
});
export type MovieGenreInput = __Infer<typeof MovieGenreInput>;

export const Org = __t.object("Org", {
  avatarId: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  id: __t.u32(),
  name: __t.string(),
  slug: __t.string(),
  updatedAt: __t.timestamp(),
  userId: __t.identity(),
});
export type Org = __Infer<typeof Org>;

export const OrgInvite = __t.object("OrgInvite", {
  createdAt: __t.timestamp(),
  email: __t.string(),
  expiresAt: __t.f64(),
  id: __t.u32(),
  isAdmin: __t.bool(),
  orgId: __t.u32(),
  token: __t.string(),
});
export type OrgInvite = __Infer<typeof OrgInvite>;

export const OrgJoinRequest = __t.object("OrgJoinRequest", {
  createdAt: __t.timestamp(),
  id: __t.u32(),
  message: __t.option(__t.string()),
  orgId: __t.u32(),
  status: __t.string(),
  updatedAt: __t.timestamp(),
  userId: __t.identity(),
});
export type OrgJoinRequest = __Infer<typeof OrgJoinRequest>;

export const OrgMember = __t.object("OrgMember", {
  createdAt: __t.timestamp(),
  id: __t.u32(),
  isAdmin: __t.bool(),
  orgId: __t.u32(),
  updatedAt: __t.timestamp(),
  userId: __t.identity(),
});
export type OrgMember = __Infer<typeof OrgMember>;

export const OrgProfile = __t.object("OrgProfile", {
  avatar: __t.option(__t.string()),
  bio: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  displayName: __t.string(),
  notifications: __t.bool(),
  theme: __t.string(),
  updatedAt: __t.timestamp(),
  userId: __t.identity(),
});
export type OrgProfile = __Infer<typeof OrgProfile>;

export const Project = __t.object("Project", {
  createdAt: __t.timestamp(),
  description: __t.option(__t.string()),
  editors: __t.option(__t.array(__t.identity())),
  id: __t.u32(),
  name: __t.string(),
  orgId: __t.u32(),
  status: __t.option(__t.string()),
  updatedAt: __t.timestamp(),
  userId: __t.identity(),
});
export type Project = __Infer<typeof Project>;

export const Task = __t.object("Task", {
  assigneeId: __t.option(__t.identity()),
  completed: __t.option(__t.bool()),
  createdAt: __t.timestamp(),
  id: __t.u32(),
  orgId: __t.u32(),
  priority: __t.option(__t.string()),
  projectId: __t.u32(),
  title: __t.string(),
  updatedAt: __t.timestamp(),
  userId: __t.identity(),
});
export type Task = __Infer<typeof Task>;

export const Wiki = __t.object("Wiki", {
  content: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  deletedAt: __t.option(__t.timestamp()),
  editors: __t.option(__t.array(__t.identity())),
  id: __t.u32(),
  orgId: __t.u32(),
  slug: __t.string(),
  status: __t.string(),
  title: __t.string(),
  updatedAt: __t.timestamp(),
  userId: __t.identity(),
});
export type Wiki = __Infer<typeof Wiki>;
