import { strictApi } from '@a/shared/strict-api'
export { guardApi } from './guard'
export { identityEquals, identityFromHex, identityToHex, idFromWire, idToWire } from './server/helpers'
export type {
  Ab,
  ActionCtxLike,
  AuthorInfo,
  BaseSchema,
  CacheCrudResult,
  CacheOptions,
  CanEditOpts,
  CascadeOption,
  ChildConfig,
  ChildCrudResult,
  ComparisonOp,
  CrudHooks,
  CrudOptions,
  CrudReadApi,
  CrudResult,
  DbLike,
  DbReadLike,
  DocBase,
  EnrichedDoc,
  ErrorCode,
  FID,
  HookCtx,
  InferCreate,
  InferReducerArgs,
  InferReducerInputs,
  InferReducerOutputs,
  InferReducerReturn,
  InferRow,
  InferRows,
  InferUpdate,
  Mb,
  MutationCtxLike,
  OrgCrudResult,
  OrgDefSchema,
  OrgEnrichedDoc,
  OrgRole,
  OrgSchema,
  OwnedSchema,
  PaginatedResult,
  PaginationOptsShape,
  Qb,
  QueryCtxLike,
  QueryLike,
  ReadCtx,
  Register,
  RegisteredDefaultError,
  RegisteredMeta,
  SchemaPhantoms,
  SetupConfig,
  SingletonSchema,
  StorageLike,
  WhereGroupOf,
  WhereOf,
  WithUrls
} from './server/types'
export { zodFromTable } from './stdb-zod'
export type { StrictApi } from '@a/shared/strict-api'
export { strictApi }
