// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  MovieGenreInput,
} from "./types";
export default {
  tmdbId: __t.f64(),
  backdropPath: __t.option(__t.string()),
  budget: __t.option(__t.f64()),
  get genres() {
    return __t.array(MovieGenreInput);
  },
  originalTitle: __t.string(),
  overview: __t.string(),
  posterPath: __t.option(__t.string()),
  releaseDate: __t.string(),
  revenue: __t.option(__t.f64()),
  runtime: __t.option(__t.f64()),
  tagline: __t.option(__t.string()),
  title: __t.string(),
  voteAverage: __t.f64(),
  voteCount: __t.f64(),
};
