// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  MessagePart,
} from "./types";


export default __t.row({
  chatId: __t.u32().name("chat_id"),
  createdAt: __t.timestamp().name("created_at"),
  id: __t.u32().primaryKey(),
  get parts() {
    return __t.array(MessagePart);
  },
  role: __t.string(),
  updatedAt: __t.timestamp().name("updated_at"),
  userId: __t.identity().name("user_id"),
});
