// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  MovieGenre,
} from "./types";
export default __t.row({
  backdropPath: __t.option(__t.string()).name("backdrop_path"),
  budget: __t.option(__t.f64()),
  cachedAt: __t.timestamp().name("cached_at"),
  createdAt: __t.timestamp().name("created_at"),
  get genres() {
    return __t.array(MovieGenre);
  },
  id: __t.u32().primaryKey(),
  invalidatedAt: __t.option(__t.timestamp()).name("invalidated_at"),
  originalTitle: __t.string().name("original_title"),
  overview: __t.string(),
  posterPath: __t.option(__t.string()).name("poster_path"),
  releaseDate: __t.string().name("release_date"),
  revenue: __t.option(__t.f64()),
  runtime: __t.option(__t.f64()),
  tagline: __t.option(__t.string()),
  title: __t.string(),
  tmdbId: __t.u32().name("tmdb_id"),
  updatedAt: __t.timestamp().name("updated_at"),
  voteAverage: __t.f64().name("vote_average"),
  voteCount: __t.f64().name("vote_count"),
});
