// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
export default __t.row({
  createdAt: __t.timestamp().name("created_at"),
  description: __t.option(__t.string()),
  editors: __t.option(__t.array(__t.identity())),
  id: __t.u32().primaryKey(),
  name: __t.string(),
  orgId: __t.u32().name("org_id"),
  status: __t.option(__t.string()),
  updatedAt: __t.timestamp().name("updated_at"),
  userId: __t.identity().name("user_id"),
});
