// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
export default __t.row({
  assigneeId: __t.option(__t.identity()).name("assignee_id"),
  completed: __t.option(__t.bool()),
  createdAt: __t.timestamp().name("created_at"),
  id: __t.u32().primaryKey(),
  orgId: __t.u32().name("org_id"),
  priority: __t.option(__t.string()),
  projectId: __t.u32().name("project_id"),
  title: __t.string(),
  updatedAt: __t.timestamp().name("updated_at"),
  userId: __t.identity().name("user_id"),
});
