// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  content: __t.option(__t.string()),
  createdAt: __t.timestamp().name("created_at"),
  deletedAt: __t.option(__t.timestamp()).name("deleted_at"),
  editors: __t.option(__t.array(__t.identity())),
  id: __t.u32().primaryKey(),
  orgId: __t.u32().name("org_id"),
  slug: __t.string(),
  status: __t.string(),
  title: __t.string(),
  updatedAt: __t.timestamp().name("updated_at"),
  userId: __t.identity().name("user_id"),
});
