/* eslint-disable */
import { type Infer as __Infer } from "spacetimedb";
import CreateBlogReducer from "../create_blog_reducer";
import RmBlogReducer from "../rm_blog_reducer";
import UpdateBlogReducer from "../update_blog_reducer";
import CreateChatReducer from "../create_chat_reducer";
import RmChatReducer from "../rm_chat_reducer";
import UpdateChatReducer from "../update_chat_reducer";
import CreatePollReducer from "../create_poll_reducer";
import RmPollReducer from "../rm_poll_reducer";
import UpdatePollReducer from "../update_poll_reducer";
import CreateProjectReducer from "../create_project_reducer";
import RmProjectReducer from "../rm_project_reducer";
import UpdateProjectReducer from "../update_project_reducer";
import CreateTaskReducer from "../create_task_reducer";
import RmTaskReducer from "../rm_task_reducer";
import UpdateTaskReducer from "../update_task_reducer";
import CreateWikiReducer from "../create_wiki_reducer";
import RmWikiReducer from "../rm_wiki_reducer";
import UpdateWikiReducer from "../update_wiki_reducer";
import GetBlogProfileReducer from "../get_blog_profile_reducer";
import UpsertBlogProfileReducer from "../upsert_blog_profile_reducer";
import GetOrgProfileReducer from "../get_org_profile_reducer";
import UpsertOrgProfileReducer from "../upsert_org_profile_reducer";
import GetPollProfileReducer from "../get_poll_profile_reducer";
import UpsertPollProfileReducer from "../upsert_poll_profile_reducer";
import CreateMovieReducer from "../create_movie_reducer";
import InvalidateMovieReducer from "../invalidate_movie_reducer";
import PurgeMovieReducer from "../purge_movie_reducer";
import RmMovieReducer from "../rm_movie_reducer";
import UpdateMovieReducer from "../update_movie_reducer";
import CreateMessageReducer from "../create_message_reducer";
import RmMessageReducer from "../rm_message_reducer";
import UpdateMessageReducer from "../update_message_reducer";
import DeleteFileFileReducer from "../delete_file_file_reducer";
import RegisterUploadFileReducer from "../register_upload_file_reducer";
import OrgCreateReducer from "../org_create_reducer";
import OrgRemoveReducer from "../org_remove_reducer";
import OrgUpdateReducer from "../org_update_reducer";
import OrgLeaveReducer from "../org_leave_reducer";
import OrgRemoveMemberReducer from "../org_remove_member_reducer";
import OrgSetAdminReducer from "../org_set_admin_reducer";
import OrgTransferOwnershipReducer from "../org_transfer_ownership_reducer";
import OrgAcceptInviteReducer from "../org_accept_invite_reducer";
import OrgRevokeInviteReducer from "../org_revoke_invite_reducer";
import OrgSendInviteReducer from "../org_send_invite_reducer";
import OrgApproveJoinReducer from "../org_approve_join_reducer";
import OrgCancelJoinReducer from "../org_cancel_join_reducer";
import OrgRejectJoinReducer from "../org_reject_join_reducer";
import OrgRequestJoinReducer from "../org_request_join_reducer";
import AppendVoteReducer from "../append_vote_reducer";
import PurgeVoteByParentReducer from "../purge_vote_by_parent_reducer";
import RestoreVoteByParentReducer from "../restore_vote_by_parent_reducer";
import BulkAppendVoteReducer from "../bulk_append_vote_reducer";
import UpdateVoteReducer from "../update_vote_reducer";
import RmVoteReducer from "../rm_vote_reducer";
import BulkRmVoteReducer from "../bulk_rm_vote_reducer";
import RmSiteConfigReducer from "../rm_site_config_reducer";
import SetSiteConfigReducer from "../set_site_config_reducer";
import RestoreSiteConfigReducer from "../restore_site_config_reducer";
import ConsumePollVoteQuotaReducer from "../consume_poll_vote_quota_reducer";
import RecordPollVoteQuotaReducer from "../record_poll_vote_quota_reducer";
import CleanupTestDataReducer from "../cleanup_test_data_reducer";
export type CreateBlogParams = __Infer<typeof CreateBlogReducer>;
export type RmBlogParams = __Infer<typeof RmBlogReducer>;
export type UpdateBlogParams = __Infer<typeof UpdateBlogReducer>;
export type CreateChatParams = __Infer<typeof CreateChatReducer>;
export type RmChatParams = __Infer<typeof RmChatReducer>;
export type UpdateChatParams = __Infer<typeof UpdateChatReducer>;
export type CreatePollParams = __Infer<typeof CreatePollReducer>;
export type RmPollParams = __Infer<typeof RmPollReducer>;
export type UpdatePollParams = __Infer<typeof UpdatePollReducer>;
export type CreateProjectParams = __Infer<typeof CreateProjectReducer>;
export type RmProjectParams = __Infer<typeof RmProjectReducer>;
export type UpdateProjectParams = __Infer<typeof UpdateProjectReducer>;
export type CreateTaskParams = __Infer<typeof CreateTaskReducer>;
export type RmTaskParams = __Infer<typeof RmTaskReducer>;
export type UpdateTaskParams = __Infer<typeof UpdateTaskReducer>;
export type CreateWikiParams = __Infer<typeof CreateWikiReducer>;
export type RmWikiParams = __Infer<typeof RmWikiReducer>;
export type UpdateWikiParams = __Infer<typeof UpdateWikiReducer>;
export type GetBlogProfileParams = __Infer<typeof GetBlogProfileReducer>;
export type UpsertBlogProfileParams = __Infer<typeof UpsertBlogProfileReducer>;
export type GetOrgProfileParams = __Infer<typeof GetOrgProfileReducer>;
export type UpsertOrgProfileParams = __Infer<typeof UpsertOrgProfileReducer>;
export type GetPollProfileParams = __Infer<typeof GetPollProfileReducer>;
export type UpsertPollProfileParams = __Infer<typeof UpsertPollProfileReducer>;
export type CreateMovieParams = __Infer<typeof CreateMovieReducer>;
export type InvalidateMovieParams = __Infer<typeof InvalidateMovieReducer>;
export type PurgeMovieParams = __Infer<typeof PurgeMovieReducer>;
export type RmMovieParams = __Infer<typeof RmMovieReducer>;
export type UpdateMovieParams = __Infer<typeof UpdateMovieReducer>;
export type CreateMessageParams = __Infer<typeof CreateMessageReducer>;
export type RmMessageParams = __Infer<typeof RmMessageReducer>;
export type UpdateMessageParams = __Infer<typeof UpdateMessageReducer>;
export type DeleteFileFileParams = __Infer<typeof DeleteFileFileReducer>;
export type RegisterUploadFileParams = __Infer<typeof RegisterUploadFileReducer>;
export type OrgCreateParams = __Infer<typeof OrgCreateReducer>;
export type OrgRemoveParams = __Infer<typeof OrgRemoveReducer>;
export type OrgUpdateParams = __Infer<typeof OrgUpdateReducer>;
export type OrgLeaveParams = __Infer<typeof OrgLeaveReducer>;
export type OrgRemoveMemberParams = __Infer<typeof OrgRemoveMemberReducer>;
export type OrgSetAdminParams = __Infer<typeof OrgSetAdminReducer>;
export type OrgTransferOwnershipParams = __Infer<typeof OrgTransferOwnershipReducer>;
export type OrgAcceptInviteParams = __Infer<typeof OrgAcceptInviteReducer>;
export type OrgRevokeInviteParams = __Infer<typeof OrgRevokeInviteReducer>;
export type OrgSendInviteParams = __Infer<typeof OrgSendInviteReducer>;
export type OrgApproveJoinParams = __Infer<typeof OrgApproveJoinReducer>;
export type OrgCancelJoinParams = __Infer<typeof OrgCancelJoinReducer>;
export type OrgRejectJoinParams = __Infer<typeof OrgRejectJoinReducer>;
export type OrgRequestJoinParams = __Infer<typeof OrgRequestJoinReducer>;
export type AppendVoteParams = __Infer<typeof AppendVoteReducer>;
export type PurgeVoteByParentParams = __Infer<typeof PurgeVoteByParentReducer>;
export type RestoreVoteByParentParams = __Infer<typeof RestoreVoteByParentReducer>;
export type BulkAppendVoteParams = __Infer<typeof BulkAppendVoteReducer>;
export type UpdateVoteParams = __Infer<typeof UpdateVoteReducer>;
export type RmVoteParams = __Infer<typeof RmVoteReducer>;
export type BulkRmVoteParams = __Infer<typeof BulkRmVoteReducer>;
export type RmSiteConfigParams = __Infer<typeof RmSiteConfigReducer>;
export type SetSiteConfigParams = __Infer<typeof SetSiteConfigReducer>;
export type RestoreSiteConfigParams = __Infer<typeof RestoreSiteConfigReducer>;
export type ConsumePollVoteQuotaParams = __Infer<typeof ConsumePollVoteQuotaReducer>;
export type RecordPollVoteQuotaParams = __Infer<typeof RecordPollVoteQuotaReducer>;
export type CleanupTestDataParams = __Infer<typeof CleanupTestDataReducer>;
