const SWIFT_KEYWORDS = new Set([
    'Any',
    'as',
    'associatedtype',
    'break',
    'case',
    'catch',
    'class',
    'continue',
    'default',
    'defer',
    'deinit',
    'do',
    'else',
    'enum',
    'extension',
    'fallthrough',
    'false',
    'fileprivate',
    'for',
    'func',
    'guard',
    'if',
    'import',
    'in',
    'init',
    'inout',
    'internal',
    'is',
    'let',
    'nil',
    'open',
    'operator',
    'override',
    'precedencegroup',
    'private',
    'Protocol',
    'protocol',
    'public',
    'repeat',
    'required',
    'rethrows',
    'return',
    'Self',
    'self',
    'static',
    'struct',
    'subscript',
    'super',
    'switch',
    'throw',
    'throws',
    'true',
    'try',
    'Type',
    'typealias',
    'var',
    'where',
    'while'
  ]),
  SWIFT_IDENT_RE = /^[a-zA-Z_][a-zA-Z0-9_]*$/u,
  DIGIT_START_RE = /^[0-9]/u,
  NON_ALNUM_RE = /[^a-zA-Z0-9_]/gu,
  isValidSwiftIdent = (s: string): boolean => SWIFT_IDENT_RE.test(s) && !SWIFT_KEYWORDS.has(s),
  swiftEnumCase = (v: string): string => {
    if (isValidSwiftIdent(v)) return `case ${v}`
    if (SWIFT_KEYWORDS.has(v)) return `case \`${v}\``
    const safe = v.replaceAll(NON_ALNUM_RE, '_'),
      ident = DIGIT_START_RE.test(safe) ? `_${safe}` : safe
    return `case ${ident} = "${v}"`
  }

export { isValidSwiftIdent, SWIFT_KEYWORDS, swiftEnumCase }
