const log = (msg: string) => process.stdout.write(`${msg}\n`)
log('=== noboil full setup (both databases) ===\n')
log('Running setup-convex...\n')
await import('./setup-convex')
log('\nRunning setup-spacetimedb...\n')
await import('./setup-spacetimedb')
log('\n=== Both databases ready ===')
